// src/components/ui-kit/CardTitle.tsx
import { cn } from '@/lib/utils';

export function CardTitle({ children, spaceBetween = false, className = '' }) {
	return (
		<h3
			className={cn(
				'm-0 mb-0.5 flex w-full flex-row items-center text-[1.17em] font-semibold',
				spaceBetween ? 'justify-between' : 'justify-start',
				className,
			)}
		>
			{children}
		</h3>
	);
}

// components/cardTitle.vue
<template>
  <h3 class="card-title" :class="{spaceBetween}">
    <slot />
  </h3>
</template>
<script>
export default {
  props: {
    spaceBetween: {
      type: Boolean,
      default: false
    }
  }
}
</script>
<style lang="sass" scoped>
.card-title
  margin: 0
  line-height: 18px
  margin-bottom: 2px
  width: 100%
  display: flex
  align-items: center
  flex-direction: row
  justify-content: flex-start
  &.spaceBetween
    justify-content: space-between
</style>
