// src/components/ui-kit/Card.tsx
import { Link } from '@tanstack/react-router';
import { useEffect, useRef } from 'react';
import type React from 'react';
import { bindInteractiveCard } from '@/lib/motion';
import { cn } from '@/lib/utils';

type CardProps = {
	to?: string;
	className?: string;
	children?: React.ReactNode;
} & React.HTMLAttributes<HTMLElement>;

export function Card({ to, className = '', children, ...props }: CardProps) {
	const cardRef = useRef<HTMLElement | null>(null);
	const isHoverable = /\bhoverable\b/.test(className);
	const isPadding = /\bpadding\b/.test(className);
	const isBorderless = /\bborderless\b/.test(className);
	const isInteractive = isHoverable || Boolean(to);
	const normalizedClassName = normalizeCardClassName(className, isInteractive);
	const classes = cn(
		'relative w-full overflow-hidden rounded-lg !text-black !no-underline transition-colors duration-200 dark:!text-white',
		'[&_p]:!m-0 [&_p]:!text-[0.85rem] [&_p]:!opacity-80 [&_p+p]:!mt-2',
		'[&>[data-card-icon]]:absolute [&>[data-card-icon]]:right-2 [&>[data-card-icon]]:bottom-0 [&>[data-card-icon]]:m-auto [&>[data-card-icon]]:size-12 [&>[data-card-icon]]:origin-bottom-right [&>[data-card-icon]]:opacity-20',
		isBorderless ? 'border-0 bg-transparent shadow-none' : 'bg-[rgb(var(--vs-background))]',
		!isBorderless && isInteractive
			? 'shadow-[0_5px_20px_0_rgba(0,0,0,var(--vs-shadow-opacity,0.05))]'
			: !isBorderless && 'border border-[rgba(var(--vs-text),0.1)] shadow-none',
		isBorderless ? 'px-0 py-1' : isPadding ? 'px-4 py-3' : 'px-3 py-2',
		isInteractive &&
			'cursor-pointer will-change-transform hover:!text-black dark:hover:!text-white',
		normalizedClassName,
	);

	useEffect(() => {
		if (!isInteractive) return undefined;
		return bindInteractiveCard(cardRef.current);
	}, [isInteractive]);

	if (to) {
		return (
			<Link ref={cardRef as React.Ref<HTMLAnchorElement>} to={to} className={classes} {...props}>
				{children}
			</Link>
		);
	}
	return (
		<div ref={cardRef as React.Ref<HTMLDivElement>} className={classes} {...props}>
			{children}
		</div>
	);
}

function normalizeCardClassName(className: string, isInteractive: boolean) {
	const baseClasses = className
		.replace(/\bhoverable\b|\bpadding\b|\bborderless\b/g, '')
		.split(/\s+/)
		.filter(Boolean);

	if (!isInteractive) return baseClasses.join(' ');

	return baseClasses
		.filter((item) => {
			if (item === 'cursor-pointer') return false;
			if (item === 'transition-transform') return false;
			if (item === 'transition-all') return false;
			if (item === 'active:shadow-none') return false;
			if (item.startsWith('hover:-translate-y')) return false;
			if (item.startsWith('active:translate-y')) return false;
			if (item.startsWith('hover:shadow-')) return false;
			return true;
		})
		.join(' ');
}

// components/card.vue
<template>
  <div class="card" :is="to ? 'router-link' : 'div'" :to="to">
    <slot />
  </div>
</template>
<script>
export default {
  name: 'card',
  props: {
    to: {
      type: String
    }
  }
}
</script>
<style lang="sass">
.card
    background: #fff
    background: rgba(var(--vs-background),1)
    color: #2c3e50
    width: 100%
    box-shadow: 0 5px 20px 0 rgba(0,0,0,var(--vs-shadow-opacity,.05))
    border-radius: 12px
    transition: all .25s ease
    position: relative
    padding: 6px 8px
    overflow: hidden
    text-decoration: none
    &[disabled]
        pointer-events: none
    &:not(.hoverable)
        box-shadow: 0 0px 0px 1px rgba(0,0,0,.05)
    &.borderless
        box-shadow: none
        background: transparent
        padding: 4px 0px
    &.padding
        padding: 12px 16px
    &.hoverable
        cursor: pointer

        &>i
            transform: translateY(20%)
        &:hover
            box-shadow: 0 10px 20px 0 rgba(0,0,0,var(--vs-shadow-opacity,.05))
            transform: translate(0, -5px)
            color: #2c3e50
            &>i
                opacity: .4
                transform: none
        &:active
            box-shadow: 0px 0px 0px 0px rgba(0, 0, 0, var(--vs-shadow-opacity,0))
            transform: translate(0, 5px)
    p
        margin: 0
        opacity: 0.8
        font-size: 0.85rem
        &+p
            margin-top: 8px
    &>i
        position: absolute
        bottom: 0
        right: .1em
        font-size: 48px
        opacity: .2
        transition: all .25s ease
        margin: auto
        transform-origin: bottom right
</style>
