// components/universal-search.vue
<template>
  <div class="search-box-container" :class="{ navbar }">
    <div class="search-box">
      <input
        type="text"
        placeholder="搜尋課程、教師或是班級⋯"
        ref="searchInput"
        v-model="searchInput"
        @input="searchInputChange"
        @focus="onFocus"
        @blur="onBlur"
        @keydown.down.prevent="onArrowDown"
        @keydown.up.prevent="onArrowUp"
        @keydown.enter.tab.prevent="selectCurrentSelection"
        @keydown.esc.prevent="onEsc"
        @mouseenter="currentSelectionIndex = -1"
        autocomplete="off" />
      <button v-if="searchInput.length" @click="searchInput = ''">
        <i class='bx bx-x'></i>
      </button>
      <button v-else>
        <i class='bx bx-loader-alt bx-spin' v-if="loading"></i>
        <i class='bx bx-search' v-else></i>
      </button>
    </div>
    <div class="search-autocomplete-items">
      <div
        class="search-autocomplete-item"
        :class="{ focus: currentSelectionIndex == i }"
        v-for="(item, i) of searchAutocompleteItems"
        :key="item.id"
        @click="selectItem(item)"
        @mousedown.prevent
        @mouseenter="currentSelectionIndex = i">
        <div class="search-autocomplete-item-content">
          <div class="search-autocomplete-item-category">
            {{ item.category }}
          </div>
          <div class="search-autocomplete-item-text">
            {{ item.text }}
          </div>
        </div>
        <div class="search-autocomplete-item-icon" v-if="item.history">
          <i class='bx bx-right-arrow-alt' v-if="currentSelectionIndex == i" />
          <i class='bx bx-history' v-else />
        </div>
        <div class="search-autocomplete-item-icon" v-else>
          <i class='bx bx-right-arrow-alt' />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      searchInput: '',
      searchAutocompleteItems: [],
      currentSelectionIndex: -1,
      loading: false,
    }
  },
  mounted() {
    this.loadSearchHistory()
  },
  watch: {
    currentSelectionIndex() {
      if (this.currentSelectionIndex >= 0) {
        this.scrollSelectionIntoView()
      }
    },
    year(newCount, oldCount) {
      this.fetchCourseData()
    },
    sem(newCount, oldCount) {
      this.fetchCourseData()
    }
  },
  props: {
    navbar: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    loadSearchHistory() {
      this.searchAutocompleteItems = JSON.parse(localStorage[`search-history`] || '[]').reverse()
    },
    async fetchCourseData() {
      this.loading = true
      if (!this.courseData) {
        this.courseData = await this.$fetchCourse()
      }
      this.loading = false
      return this.courseData
    },
    async searchInputChange() {
      function genRandomId() {
        return Math.random().toString(36).substring(2, 15)
      }
      let year = localStorage[`data-year`]
      let sem = localStorage[`data-sem`]
      let department = localStorage[`data-department`]
      let courses = await this.fetchCourseData()
      let val = this.searchInput
      try {
        val = val.toLowerCase()
      } catch (e) { }
      let searchAutocompleteItems = []
      if (val) {
        let keywords = val.split(' ')
        // is number
        // 課號
        if (!isNaN(val) && val.length >= 3) {
          searchAutocompleteItems.push(
            ...courses
              .filter(course => course.id.includes(val))
              .map(course => ({
                id: `${year}/${sem}/${course.id}`,
                type: 'course',
                to: `/course/${year}/${sem}/${course.id}`,
                category: course.id,
                text: course.name.zh,
                //course,
              })).slice(0, 10)
          )
        }
        // 班級
        searchAutocompleteItems.push(
          ...Array.from(
            new Set(courses
              .map(course => course.class)
              .flat(2)
              .map(x => x.name)
              .filter(x => x.toLowerCase().includes(val))
            )
          )
            .map(x => ({
              id: `${x}?year=${year}&sem=${sem}&d=${department}`,
              type: 'class',
              to: `/class/${x}?year=${year}&sem=${sem}&d=${department}`,
              category: `班級`,
              text: x,
            }))
            .slice(0, 10)
        )
        // 教師
        searchAutocompleteItems.push(
          ...Array.from(
            new Set(courses
              .map(course => course.teacher)
              .flat(2)
              .map(x => x.name)
              .filter(x => x.toLowerCase().includes(val))
            )
          )
            .map(x => ({
              id: `teacher/${x}`,
              type: 'teacher',
              to: `/teacher/${x}`,
              category: `教師`,
              text: x,
            }))
            .slice(0, 10)
        )
        // 課程名稱、教師名稱
        let autocompleteCourses = courses
        for (let keyword of keywords) {
          autocompleteCourses = autocompleteCourses.filter(course =>
            course.name?.zh.toLowerCase().includes(keyword) ||
            course.name?.en.toLowerCase().includes(keyword) ||
            course.teacher.map(x => x.name).join(' ').toLowerCase().includes(keyword) ||
            course.class.map(x => x.name).join(' ').toLowerCase().includes(keyword)
          )
        }
        searchAutocompleteItems.push(...autocompleteCourses
          .map(course => ({
            id: `${year}/${sem}/${course.id}`,
            type: 'course',
            to: `/course/${year}/${sem}/${course.id}`,
            category: `${course.id} ${course.teacher.map(x => x.name).join(' ')}`,
            text: course.name.zh,
            course,
          }))
          .sort((a, b) => keywords.some(x => a.text.toLowerCase().includes(x)) ? -1 : 1)
          .slice(0, 20)
        )

        this.searchAutocompleteItems = searchAutocompleteItems.slice(0, 50)
      } else {
        this.loadSearchHistory()
      }
      this.currentSelectionIndex = -1
    },
    scrollSelectionIntoView() {
      this.$nextTick(() => {
        const active_node = document.querySelector(`.search-autocomplete-items .search-autocomplete-item.focus`);
        active_node.scrollIntoView({
          behavior: 'smooth',
          block: 'nearest',
          inline: 'nearest',
        });
      });
    },
    onArrowUp() {
      if (this.currentSelectionIndex >= 0) {
        this.currentSelectionIndex--
      }
    },
    onArrowDown() {
      if (this.currentSelectionIndex < this.searchAutocompleteItems.length - 1) {
        this.currentSelectionIndex++
      }
    },
    onFocus() {
      this.currentSelectionIndex = -1
    },
    onBlur() {
      this.currentSelectionIndex = -1
    },
    onEsc() {
      this.currentSelectionIndex = -1
      this.$refs.searchInput.blur()
    },
    selectCurrentSelection() {
      if (this.currentSelectionIndex >= 0) {
        this.selectItem(this.searchAutocompleteItems[this.currentSelectionIndex])
      }
    },
    selectItem(item) {
      let searchHistory = JSON.parse(localStorage[`search-history`] || '[]')
      searchHistory.push({ ...item, history: true })
      searchHistory = searchHistory.slice(-10).reverse().filter((x, i, a) => a.findIndex(y => y.id === x.id) === i).reverse()
      localStorage[`search-history`] = JSON.stringify(searchHistory)
      if (item.to) {
        this.$router.push(item.to)
        this.onEsc()
      }
    }
  },
}
</script>

<style lang="sass" scoped>
.search-box-container
  position: relative
  width: 100%
  margin: 0 auto
  &.navbar
    width: 512px
    @media screen and (max-width: 768px)
      width: 324px
  .search-box
    display: flex
    border-radius: 8px
    background: rgba(var(--vs-text), .1)
    border: 1px solid rgba(var(--vs-text), 0)
    transition: all .2s ease
    @media (prefers-color-scheme: dark)
      background: rgba(var(--vs-text), .05)
    &:hover
      background: rgba(var(--vs-text), .05)
      @media (prefers-color-scheme: dark)
        background: rgba(var(--vs-text), .075)
    &:has(input:focus)
      background: rgba(var(--vs-gray-1), 1)
      border: 1px solid rgba(var(--vs-gray-4), 1)
      box-shadow: 0 5px 20px 0 rgba(0,0,0,var(--vs-shadow-opacity,.05))
      @media (prefers-color-scheme: dark)
        background-color: rgba(var(--vs-background), 1)
        border: 1px solid rgba(var(--vs-text), .05)
    input,
    button
      border: none
      outline: none
      padding: 16px 24px
      background-color: transparent
      font-size: 16px
      color: rgba(var(--vs-text), 1)
    input
      flex: 1
    button
      cursor: pointer
      color: rgba(var(--vs-text), .8)
      display: flex
      align-items: center
      justify-content: center
      transition: all .2s ease
      i
        font-size: 24px
      &:hover
        color: rgba(var(--vs-text), 1)
      &:active
        transform: scale(.9)

  &.navbar
    .search-box
      margin: 4px 0
      input,
      button
        padding: 8px 16px
  .search-autocomplete-items
    position: absolute
    border-radius: 8px
    background-color: rgba(var(--vs-background), 1)
    width: 100%
    margin-top: 8px
    box-shadow: 0 20px 20px 0 rgba(0,0,0,var(--vs-background-opacity,.02))
    max-height: 512px
    overflow-y: auto
    transition: all .2s ease
    z-index: 1

    opacity: 0
    transform: translateY(-8px)
    pointer-events: none
    @media screen and (max-width: 768px)
      max-height: 256px
    .search-autocomplete-item
      display: flex
      align-items: center
      cursor: pointer
      overflow: hidden
      &:not(:first-child)
        border-top: 1px solid rgba(var(--vs-gray-4), 1)
        @media (prefers-color-scheme: dark)
          border-top: 1px solid rgba(var(--vs-text), .1)
      &.focus
        background: rgba(var(--vs-text), .05)
        .search-autocomplete-item-icon
          transform: translateX(3px)
      .search-autocomplete-item-content
        flex: 1
        padding: 16px 24px
        .search-autocomplete-item-category
          font-size: 12px
          opacity: .8
        .search-autocomplete-item-text
          font-size: 16px
          font-weight: bold
      .search-autocomplete-item-icon
        padding: 16px 24px
        transition: all .2s ease
        i
          font-size: 24px

  &:has(input:focus)
    .search-autocomplete-items
      opacity: 1
      transform: none
      pointer-events: all
</style>

// src/components/UniversalSearch.tsx
import { Link, useNavigate } from '@tanstack/react-router'
import { useEffect, useMemo, useRef, useState } from 'react'
import { cn } from '../lib/utils'
import { courseTitle, searchCourseList } from '../lib/courseUtils'
import { animateSearchResults } from '../lib/motion'
import { useApp } from '../state/AppContext'
import type { Course, SearchHistoryItem } from '../types/course'

export function UniversalSearch({ navbar = false, className = '' }) {
  const { dataset, getCourses } = useApp()
  const navigate = useNavigate()
  const inputRef = useRef<HTMLInputElement | null>(null)
  const resultsRef = useRef<HTMLDivElement | null>(null)
  const [input, setInput] = useState('')
  const [courseData, setCourseData] = useState<Course[] | null>(null)
  const [focused, setFocused] = useState(false)
  const [loading, setLoading] = useState(false)
  const [currentSelectionIndex, setCurrentSelectionIndex] = useState(-1)

  useEffect(() => {
    let cancelled = false
    if (!focused && !input) return undefined
    setLoading(true)
    getCourses()
      .then((data) => {
        if (!cancelled) setCourseData(data)
      })
      .catch(() => {
        if (!cancelled) setCourseData([])
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [dataset.year, dataset.sem, dataset.department, focused, input, getCourses])

  const items = useMemo(() => {
    if (!input) return JSON.parse(localStorage.getItem('search-history') || '[]').reverse()
    if (!courseData) return []
    const courses = searchCourseList(courseData, input).slice(0, 20)
    return courses.map((course) => ({
      id: course.id,
      key: `${course.id}`,
      to: `/course/${dataset.year}/${dataset.sem}/${course.id}`,
      category: `${course.id} ${(course.teacher || []).map((item) => item.name).join(' ')}`.trim(),
      text: courseTitle(course),
      description: (course.teacher || []).map((item) => item.name).join('、'),
      course,
    }))
  }, [courseData, input, dataset.year, dataset.sem])

  useEffect(() => {
    setCurrentSelectionIndex(-1)
  }, [input, focused])

  useEffect(() => {
    if (currentSelectionIndex < 0) return
    const activeNode = document.querySelector('[data-search-results] [data-active=\"true\"]')
    activeNode?.scrollIntoView?.({ behavior: 'smooth', block: 'nearest', inline: 'nearest' })
  }, [currentSelectionIndex])

  useEffect(() => {
    return animateSearchResults(resultsRef.current, focused)
  }, [focused, items.length])

  function remember(item) {
    const historyItem = { ...item, id: item.id || item.key || item.to, history: true }
    const history = JSON.parse(localStorage.getItem('search-history') || '[]').filter((entry) => entry.to !== item.to)
    localStorage.setItem('search-history', JSON.stringify([...history, historyItem].slice(-10).reverse().filter((x, index, array) => array.findIndex((y) => y.id === x.id) === index).reverse()))
    setInput('')
    setFocused(false)
    setCurrentSelectionIndex(-1)
  }

  function selectItem(item: SearchHistoryItem) {
    remember(item)
    if (item.to) navigate({ to: item.to })
  }

  function onKeyDown(event) {
    if (!items.length && event.key !== 'Escape') return
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      setCurrentSelectionIndex((value) => Math.min(value + 1, items.length - 1))
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      setCurrentSelectionIndex((value) => Math.max(value - 1, 0))
    } else if (event.key === 'Enter' || event.key === 'Tab') {
      if (currentSelectionIndex >= 0) {
        event.preventDefault()
        selectItem(items[currentSelectionIndex])
      }
    } else if (event.key === 'Escape') {
      event.preventDefault()
      inputRef.current?.blur?.()
    }
  }

  return (
    <div
      className={cn('relative mx-auto w-full', navbar ? 'max-w-[512px] md:max-w-[512px]' : 'max-w-none', className)}
    >
      <div
        className={cn(
          'flex rounded-[8px] border transition-all duration-200',
          focused
            ? 'border-[rgba(var(--vs-gray-2),1)] bg-[rgb(var(--vs-gray-1))] shadow-[0_5px_20px_0_rgba(0,0,0,var(--vs-shadow-opacity,0.05))]'
            : 'border-transparent bg-[rgba(var(--vs-text),0.1)] hover:bg-[rgba(var(--vs-text),0.05)]',
          'dark:border-[rgba(var(--vs-text),0.05)] dark:bg-[rgba(var(--vs-text),0.05)] dark:hover:bg-[rgba(var(--vs-text),0.075)]'
        )}
      >
        <input
          ref={inputRef}
          type="text"
          placeholder="搜尋課程、教師、課號、班級"
          autoComplete="off"
          value={input}
          onFocus={() => setFocused(true)}
          onBlur={() => setTimeout(() => setFocused(false), 120)}
          onPointerDown={() => setFocused(true)}
          onChange={(event) => {
            setInput(event.target.value)
            setFocused(true)
          }}
          onKeyDown={onKeyDown}
          onMouseEnter={() => setCurrentSelectionIndex(-1)}
          className={cn(
            'min-w-0 flex-1 bg-transparent text-[16px] text-[rgb(var(--vs-text))] outline-none',
            navbar ? 'px-3 py-2' : 'px-4 py-3'
          )}
        />
        <button
          type="button"
          className={cn(
            'flex shrink-0 items-center justify-center text-[rgba(var(--vs-text),0.8)] transition-all duration-200 hover:text-[rgb(var(--vs-text))]',
            navbar ? 'px-3 py-2' : 'px-4 py-3'
          )}
          onClick={() => {
            if (input) {
              setInput('')
              setCurrentSelectionIndex(-1)
              inputRef.current?.focus?.()
            }
          }}
        >
          {input ? (
            <i className="bx bx-x text-2xl" />
          ) : loading ? (
            <i className="bx bx-loader-alt bx-spin text-2xl" />
          ) : (
            <i className="bx bx-search text-2xl" />
          )}
        </button>
      </div>
      <div
        ref={resultsRef}
        data-search-results
        className={cn(
          'absolute left-0 right-0 top-full z-[999] mt-2 max-h-[512px] overflow-y-auto rounded-[8px] bg-[rgb(var(--vs-background))] shadow-[0_20px_20px_0_rgba(0,0,0,var(--vs-background-opacity,0.02))] transition-all duration-200',
          focused ? 'pointer-events-auto opacity-100' : 'pointer-events-none -translate-y-2 opacity-0',
          'max-h-[256px] md:max-h-[512px]'
        )}
      >
        {focused && items.map((item, index) => (
          <Link
            key={item.key || item.to || `${item.category}-${item.text}-${index}`}
            to={item.to || '/'}
            data-search-result-item
            data-active={currentSelectionIndex === index ? 'true' : 'false'}
            className={cn(
              'flex items-center overflow-hidden no-underline',
              'text-[rgb(var(--vs-text))]',
              index > 0 && 'border-t border-[rgba(var(--vs-gray-2),1)]',
              currentSelectionIndex === index && 'bg-[rgba(var(--vs-text),0.05)]'
            )}
            onClick={() => remember(item)}
            onMouseDown={(event) => event.preventDefault()}
            onMouseEnter={() => setCurrentSelectionIndex(index)}
          >
            <div className={cn('flex-1', navbar ? 'px-3 py-2' : 'px-4 py-3')}>
              <div className="text-xs opacity-80">{item.category || (item.history ? '歷史' : '')}</div>
              <div className="text-base font-bold">{item.text || item.label || item.name}</div>
              {item.description ? <div className="text-xs opacity-70">{item.description}</div> : null}
            </div>
            <div className={cn('transition-transform duration-200', navbar ? 'px-3 py-2' : 'px-4 py-3', currentSelectionIndex === index && 'translate-x-[3px]')}>
              {item.history ? (
                currentSelectionIndex === index ? <i className="bx bx-right-arrow-alt text-2xl" /> : <i className="bx bx-history text-2xl" />
              ) : (
                <i className="bx bx-right-arrow-alt text-2xl" />
              )}
            </div>
          </Link>
        ))}
      </div>
    </div>
  )
}
